version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: unionmarketplace/union-docker-images
      IMAGE_TAG: um-icf-grant
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG-latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG-latest
workflows:
  version: 2
  build-master:
    jobs:
      - build
